version: '3.8'

networks:
  pharmacy_network:
    external: true

services:
  redis:
    image: redis:6.2
    container_name: pharmacy-redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - pharmacy_network

  postgres:
    image: postgres:16
    container_name: pharmacy-postgres
    environment:
      POSTGRES_DB: pharmacy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    hostname: postgres
    ports:
      - "5433:5432"
    networks:
      - pharmacy_network

  pharmacy-service:
    container_name: pharmacy-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_APPLICATION_NAME: pharmacy-service
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pharmacy_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_MAIL_USERNAME:
      SPRING_MAIL_PASSWORD:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_OAUTH2_ISSUER_URI: http://pharmacy-keycloak:8080/realms/pharmacy-realm
      SPRING_KEYCLOAK_CLIENT_ID: pharmacy-client
      SPRING_KEYCLOAK_CLIENT_SECRET: rmsBgx8lzoEf7wji0NQmv5kjYL5bf9OF
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    networks:
      - pharmacy_network
