version: '3.8'

networks:
  pharmacy_network:
    external: true

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: pharmacy-keycloak
    hostname: pharmacy-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
    networks:
      - pharmacy_network
