spring:
  application:
    name: "PharmacyService"
  datasource:
    url: "jdbc:postgresql://localhost:5432/pharmacy_db"
    username: "postgres"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        show_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog_master.yaml
  mail:
    host: smtp.gmail.com
    port: 587
    username: root@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/pharmacy-realm/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/pharmacy-realm

jwt:
  auth:
    converter:
      resource-id: pharmacy-client
      principle-attribute: preferred_username

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8081
